footer: "Beep Boop, I'm a bot 🤖"
commands:
  - command: "mealie-default-credentials"
    description: "Show default credentials"
    content: |
      **Having trouble logging in?**

      Try the default username and password

      Username: changeme@example.com
      Password: MyPassword

      Btw, this is in the docs 👇

      [installation-checklist/#step-3-startup](https://nightly.mealie.io/documentation/getting-started/installation/installation-checklist/#step-3-startup)

  - command: "mealie-migration-links"
    description: "Show helpful migration links"
    content: |
      **Looking for information on Migration to v1?**

      [Beta Release Discussion](https://github.com/mealie-recipes/mealie/discussions/1073)
      [v0.5.x to v1.0.0 Migration Guide](https://nightly.mealie.io/documentation/getting-started/migrating-to-mealie-v1/)
      [Migrating from other V1 versions](https://nightly.mealie.io/documentation/getting-started/installation/installation-checklist/#migrating-from-other-v1-versions)

  - command: "mealie-docker-faq"
    description: "Show helpful Docker Problems and Solutions"
    content: |
      **Having trouble with docker?**

      1. Have you reviewed the installation checklist?
      2. Have you mapped the right container port?

      **Links**
      [Docker Compose Example](https://nightly.mealie.io/documentation/getting-started/installation/sqlite/)
      [Checklist](https://nightly.mealie.io/documentation/getting-started/installation/installation-checklist/)
      [Docker Tags](https://nightly.mealie.io/documentation/getting-started/installation/installation-checklist/#docker-tags)

  - command: "mealie-docker-tags"
    description: "Show helpful docker tags information"
    content: |
      **Not sure which tag to pull?**

      *Note: Since v1.0.0-RC1.1, Docker images have moved to GitHub*

      **<version>** - Version-specific build of Mealie.
      **v1.0.0-RC2** - Currently the latest image of Mealie
      **latest** - Latest stable release image of Mealie. *Note: This tag is not yet available, it will be available with the v1 stable release*
      **nightly** - Nightly build fresh off the mealie-next branch (if you're feeling brave)

      *See the [docker compose example](https://nightly.mealie.io/documentation/getting-started/installation/sqlite/) for most current tags for running Mealie*

      ❗Depreciated Tags❗

      **frontend-v1.0.0beta-x** and **api-v1.0.0beta-x** - These are the tags for the latest beta release of the frontend and api docker containers, respectively.
      **frontend-nightly** and **api-nightly** - These are the tags for the nightly release of the frontend and api docker containers, respectively.

      ---

      [See all available tags on GitHub](https://github.com/mealie-recipes/mealie/pkgs/container/mealie)
      [Mealie's tags documentation](https://nightly.mealie.io/documentation/getting-started/installation/installation-checklist/#docker-tags)

  - command: "mealie-token-time"
    description: "Show information about the TOKEN_TIME variable"
    content: |
      'TOKEN_TIME' is the time in hours that an auth token is valid for, it's default is set to 48 hours.

      You can change this value by setting the environment variable 'TOKEN_TIME' to a number of hours you want the token to be valid for.

      **Example:**

      environment:
        - TOKEN_TIME=999

      This will set the token to be valid for 999 hours.

  - command: "mealie-feature-request"
    description: "Show information on how to request a feature"
    content: |
      **Have a Feature Request?**

      Mealie uses GitHub discussions to track feature requests.

      If you have an idea for a feature request please head over to the discussion page!

      [Create a Feature Request](https://github.com/mealie-recipes/mealie/discussions/new?category=feature-request)
      [Open Feature Requests](https://github.com/mealie-recipes/mealie/discussions/categories/feature-request)
      [Not a Feature Request? Submit an Issue!](https://github.com/mealie-recipes/mealie/issues/new/choose)
